<?php
/**
 * PageCache powered by Varnish
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@phoenix-media.eu so we can send you a copy immediately.
 * 
 * @category   Phoenix
 * @package    Phoenix_VarnishCache
 * @copyright  Copyright (c) 2011-2014 PHOENIX MEDIA GmbH (http://www.phoenix-media.eu)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Set formkey cookie template
 *
 * @see Phoenix_VarnishCache_Block_Cookie_Formkey
 */
?>
<?php
    $_cookieName   = $this->getCookieName();
    $_formKeyValue = $this->getFormKeyValue();
?>
<script type="text/javascript">
    if (document.cookie.length && (document.cookie.indexOf('<?php echo $_cookieName; ?>=') == -1)) {
        Mage.Cookies.set(
            '<?php echo $_cookieName; ?>',
            '<?php echo $_formKeyValue; ?>',
            new Date(new Date().getTime() + <?php echo $this->getCookieLifetime(); ?>)
        );
    }
</script>
