<?php
/**
 * PageCache powered by Varnish
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the PageCache powered by Varnish License
 * that is bundled with this package in the file LICENSE_VARNISH_CACHE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.phoenix-media.eu/license/license_varnish_cache.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@phoenix-media.eu so we can send you a copy immediately.
 *
 * @category   Phoenix
 * @package    Phoenix_VarnishCache
 * @copyright  Copyright (c) 2011 PHOENIX MEDIA GmbH (http://www.phoenix-media.eu)
 * @license    http://www.phoenix-media.eu/license/license_varnish_cache.txt
 */
?>

<script type="text/javascript">
    //<![CDATA[
    function exportVcl() {
        var vclFile = $('varnishcache_export_vcl_select').getValue();
        setLocation("<?php echo $this->getExportUrl(); ?>?vcl=" + vclFile);
    }
    //]]>
</script>

<?php
    echo $this->getSelectHtml();
    echo $this->getButtonHtml();
?>